import React, { useState } from 'react';
import { Calendar, Clock, Download, Share2, Sparkles, Check, ChevronRight } from 'lucide-react';

export default function Scheduler({ user }) {
  const [weeklyGoal, setWeeklyGoal] = useState(4); // hours per week
  const [focusBasics, setFocusBasics] = useState(true);
  const [focusSpeaking, setFocusSpeaking] = useState(true);
  const [focusGrammar, setFocusGrammar] = useState(false);
  const [focusVocab, setFocusVocab] = useState(false);
  const [preferredTime, setPreferredTime] = useState('morning'); // morning, afternoon, evening
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
  const [schedule, setSchedule] = useState(null);

  // Focus topic maps
  const topicsMap = {
    basics: { title: "Letters & Alphabet Basics", desc: "Practice writing vowels/consonants and building compound symbols in the Tracing Sandbox." },
    speaking: { title: "Spoken Dialogue & Chat", desc: "Interact with Tutor Anna in Continuous Voice Chat or solve a dialogue scenario in Pronunciation Coach." },
    grammar: { title: "Spelling & Grammar Clinic", desc: "Verify conjugation rules, doubling hard consonants, and run spell-checks." },
    vocab: { title: "Video Academy & Vocab", desc: "Watch TVA Video Academy lectures and practice writing daily groceries and auto ride phrases." }
  };

  const getTargetTimeRange = (dayIndex, preferredSlot, selectedStartDate) => {
    // Determine target local hour
    let startHour = 9; // Morning 9am
    if (preferredSlot === 'afternoon') startHour = 14; // Afternoon 2pm
    if (preferredSlot === 'evening') startHour = 19; // Evening 7pm

    const date = new Date(selectedStartDate);
    date.setDate(date.getDate() + dayIndex);
    date.setHours(startHour, 0, 0, 0);

    const endDate = new Date(date);
    endDate.setMinutes(endDate.getMinutes() + 45); // 45 minute sessions

    return { start: date, end: endDate };
  };

  const formatGoogleCalendarDate = (date) => {
    // Format to YYYYMMDDTHHMMSSZ (UTC format)
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  const generateGoogleCalendarLink = (item) => {
    const startStr = formatGoogleCalendarDate(item.startTime);
    const endStr = formatGoogleCalendarDate(item.endTime);
    const title = `Tamil Study: ${item.topicTitle}`;
    const details = `${item.topicDesc}\n\nGenerated by Tamilan Anna Learning Portal. Link: http://localhost:5173`;
    
    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&dates=${startStr}/${endStr}&details=${encodeURIComponent(details)}&sf=true&output=xml`;
  };

  // Generate 7-day schedule programmatically
  const handleGenerate = (e) => {
    e.preventDefault();
    
    const activeFocusKeys = [];
    if (focusBasics) activeFocusKeys.push('basics');
    if (focusSpeaking) activeFocusKeys.push('speaking');
    if (focusGrammar) activeFocusKeys.push('grammar');
    if (focusVocab) activeFocusKeys.push('vocab');

    if (activeFocusKeys.length === 0) {
      alert("Please select at least one focus topic!");
      return;
    }

    const generatedDays = [];
    const sessionDuration = Math.round((weeklyGoal * 60) / 4); // Distribute weekly goal over 4 key study days

    // Construct 7 days study block
    for (let i = 0; i < 7; i++) {
      const isStudyDay = [1, 3, 5, 6].includes(i); // Study on Mon, Wed, Fri, Sat equivalents
      const dateObj = getTargetTimeRange(i, preferredTime, startDate);

      if (isStudyDay) {
        // Pick focus topic rotationally
        const topicKey = activeFocusKeys[i % activeFocusKeys.length];
        const topicInfo = topicsMap[topicKey];
        
        generatedDays.push({
          dayNum: i + 1,
          dateLabel: dateObj.start.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }),
          isStudy: true,
          duration: sessionDuration,
          topicKey,
          topicTitle: topicInfo.title,
          topicDesc: topicInfo.desc,
          startTime: dateObj.start,
          endTime: dateObj.end,
          timeLabel: dateObj.start.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
        });
      } else {
        generatedDays.push({
          dayNum: i + 1,
          dateLabel: dateObj.start.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }),
          isStudy: false,
          topicTitle: "Rest / Integration Day",
          topicDesc: "Take 10 minutes to review past dashboard accuracy records or read a simple story."
        });
      }
    }

    setSchedule(generatedDays);
  };

  // Download iCal (.ics) file
  const handleDownloadICS = () => {
    if (!schedule) return;

    let icsContent = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Tamilan Anna//Tamil Study Calendar//EN",
      "CALSCALE:GREGORIAN",
      "METHOD:PUBLISH"
    ];

    schedule.forEach(item => {
      if (!item.isStudy) return;

      const startStr = formatGoogleCalendarDate(item.startTime);
      const endStr = formatGoogleCalendarDate(item.endTime);
      const uid = `session-${item.dayNum}-${Date.now()}@tamilan_anna.com`;
      const title = `Tamil Study: ${item.topicTitle}`;
      const desc = item.topicDesc.replace(/,/g, '\\,');

      icsContent.push(
        "BEGIN:VEVENT",
        `UID:${uid}`,
        `DTSTART:${startStr}`,
        `DTEND:${endStr}`,
        `SUMMARY:${title}`,
        `DESCRIPTION:${desc}`,
        "STATUS:CONFIRMED",
        "END:VEVENT"
      );
    });

    icsContent.push("END:VCALENDAR");

    const icsBlob = new Blob([icsContent.join("\r\n")], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(icsBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `tamil_study_schedule_${user.username}.ics`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in" style={{ padding: '10px 0' }}>
      
      {/* Intro Header banner */}
      <div className="glass-panel" style={{ padding: '24px', background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.04) 0%, rgba(13, 148, 136, 0.03) 100%)', border: '1px solid var(--panel-border)', borderRadius: '4px', marginBottom: '24px' }}>
        <h2 style={{ fontSize: '1.4rem', color: 'var(--text-primary)', margin: '0 0 6px 0', display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 700 }}>
          <Calendar size={24} style={{ color: 'var(--accent-primary)' }} /> Language Study Scheduler
        </h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem', margin: 0, lineHeight: 1.5 }}>
          Create a personalized language study schedule distributed over the week based on your current focus parameters, then sync sessions directly to Google Calendar or export as iCal calendar logs.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.1fr 1.3fr', gap: '24px', alignItems: 'start' }}>
        
        {/* Left Column: Form Controls */}
        <div className="glass-panel" style={{ padding: '20px', background: 'white' }}>
          <h3 style={{ margin: '0 0 16px 0', fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Sparkles size={18} style={{ color: 'var(--accent-primary)' }} /> Configure Syllabus Plan
          </h3>
          <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>
                <span>WEEKLY STUDY TARGET</span>
                <span>{weeklyGoal} HOURS / WEEK</span>
              </div>
              <input
                type="range"
                min="2"
                max="12"
                step="2"
                value={weeklyGoal}
                onChange={(e) => setWeeklyGoal(parseInt(e.target.value))}
                style={{ width: '100%', cursor: 'pointer' }}
              />
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <label style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>FOCUS TOPICS</label>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: 'var(--text-primary)', cursor: 'pointer' }}>
                  <input type="checkbox" checked={focusBasics} onChange={(e) => setFocusBasics(e.target.checked)} style={{ width: '15px', height: '15px' }} />
                  <span>Alphabet & Writing Basics (உயிரெழுத்துக்கள்)</span>
                </label>
                
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: 'var(--text-primary)', cursor: 'pointer' }}>
                  <input type="checkbox" checked={focusSpeaking} onChange={(e) => setFocusSpeaking(e.target.checked)} style={{ width: '15px', height: '15px' }} />
                  <span>Speaking Scenarios & Tutor Voice Chat</span>
                </label>

                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: 'var(--text-primary)', cursor: 'pointer' }}>
                  <input type="checkbox" checked={focusGrammar} onChange={(e) => setFocusGrammar(e.target.checked)} style={{ width: '15px', height: '15px' }} />
                  <span>Spelling Rules & Grammar Clinic</span>
                </label>

                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.85rem', color: 'var(--text-primary)', cursor: 'pointer' }}>
                  <input type="checkbox" checked={focusVocab} onChange={(e) => setFocusVocab(e.target.checked)} style={{ width: '15px', height: '15px' }} />
                  <span>Vocabulary Builder & Academy Videos</span>
                </label>
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>PREFERRED STUDY TIME</label>
                <select
                  value={preferredTime}
                  onChange={(e) => setPreferredTime(e.target.value)}
                  className="form-input"
                  style={{ background: 'white' }}
                >
                  <option value="morning">Morning (09:00 AM)</option>
                  <option value="afternoon">Afternoon (02:00 PM)</option>
                  <option value="evening">Evening (07:00 PM)</option>
                </select>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <label style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>START DATE</label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  required
                  className="form-input"
                />
              </div>
            </div>

            <button type="submit" className="btn-primary" style={{ padding: '12px', justifyContent: 'center' }}>
              Generate Study Schedule
            </button>
          </form>
        </div>

        {/* Right Column: Calendar Plan Results */}
        <div className="glass-panel" style={{ padding: '20px', background: 'white', minHeight: '400px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--panel-border)', paddingBottom: '14px', marginBottom: '16px' }}>
            <h3 style={{ margin: 0, fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-primary)' }}>Interactive 7-Day Plan</h3>
            {schedule && (
              <button
                onClick={handleDownloadICS}
                className="module-action-btn"
                style={{ fontSize: '0.75rem', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Download size={14} /> Download .ics File
              </button>
            )}
          </div>

          {!schedule ? (
            <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
              <Calendar size={48} style={{ opacity: 0.15, marginBottom: '14px' }} />
              <p style={{ fontSize: '0.9rem', margin: 0 }}>Configure focus areas and click generate to view your daily learning calendar.</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {schedule.map(item => (
                <div 
                  key={item.dayNum} 
                  style={{ 
                    border: item.isStudy ? '1px solid rgba(99, 102, 241, 0.15)' : '1px solid var(--panel-border)',
                    padding: '14px', 
                    borderRadius: '4px',
                    background: item.isStudy ? 'rgba(99, 102, 241, 0.01)' : '#fcfcfd',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    gap: '16px'
                  }}
                >
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                      <span style={{ fontSize: '0.8rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>{item.dateLabel}</span>
                      {item.isStudy ? (
                        <span style={{ fontSize: '0.7rem', fontWeight: 'bold', background: 'var(--accent-secondary-glow)', color: 'var(--accent-secondary)', padding: '1px 5px', borderRadius: '2px' }}>
                          Study {item.duration}m
                        </span>
                      ) : (
                        <span style={{ fontSize: '0.7rem', fontWeight: 'bold', background: '#f1f5f9', color: '#64748b', padding: '1px 5px', borderRadius: '2px' }}>
                          Rest
                        </span>
                      )}
                    </div>
                    <h4 style={{ margin: '0 0 2px 0', fontSize: '0.92rem', fontWeight: 600, color: 'var(--text-primary)' }}>{item.topicTitle}</h4>
                    <p style={{ margin: 0, fontSize: '0.78rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>{item.topicDesc}</p>
                  </div>

                  {item.isStudy && (
                    <div style={{ textAlign: 'right', display: 'flex', flexDirection: 'column', gap: '6px', flexShrink: 0 }}>
                      <span style={{ fontSize: '0.75rem', fontWeight: 'bold', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '4px', justifyContent: 'flex-end' }}>
                        <Clock size={12} /> {item.timeLabel}
                      </span>
                      <a
                        href={generateGoogleCalendarLink(item)}
                        target="_blank"
                        rel="noreferrer"
                        className="module-action-btn"
                        style={{ fontSize: '0.7rem', padding: '4px 8px', display: 'inline-flex', alignItems: 'center', gap: '4px', background: '#ffffff', color: '#4285f4', border: '1px solid #cbd5e1' }}
                      >
                        <Share2 size={10} /> Add Google Cal
                      </a>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

        </div>

      </div>

    </div>
  );
}
